### ISSUE TITLE
Consider restricting network `driver_opts` to string values

### ISSUE THREAD

**Issue by pipex** [balena-io-modules/balena-compose#18]
While the [docker-compose specification](https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json#L664) accepts both strings and numbers, using a number seems to be rejected on the engine with a JSON unmarshaling error 

```
(HTTP code 400) unexpected - json: cannot unmarshal number into Go struct field NetworkCreateRequest.Options of type string
```

This after pushing this valid network configuration

```
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1420
```

Leaving this as an issue for discussion
