### ISSUE TITLE
Docker compose validation allows both `networks` and `network_mode`

### ISSUE THREAD

**Issue by pipex** [balena-io-modules/balena-compose#49]
The following composition is rejected by docker-compose with `service hello declares mutually exclusive `network_mode` and `networks`: invalid compose project`

```
version: '2.4'

services: 
  hello:
    image: alpine
    command: ['sleep', 'infinity']
    networks: ['my-network']
    network_mode: host


networks:
  my-network:
```

While balena-compose allows it. Making the change might prevent invalid or ambiguous compositions reaching the supervisor
