### ISSUE TITLE
Composition validation allows volumes with relative paths

### ISSUE THREAD

**Issue by pipex** [balena-io-modules/balena-compose#55]
Example 

```
version: '2'
services:
  data:
    build: ./data
    expose:
      - '8080'
    volumes:
      - my-data:./other-data
      - my-other-volume:$HOME/data

volumes:
  my-data:
  my-other-volume:
```

Is allowed by balena-compose but causes the supervisor to fail container creation with 

```
(HTTP code 500) server error - invalid volume specification
```
