### ISSUE TITLE
Raise a better error message when attempting to use bind mounts

### ISSUE THREAD

**Issue by cywang117** [balena-io-modules/balena-compose#70]
Currently, bind mounts don't fail until they get to the API, with:
```
Upstream API server/DB error: "value" is not a string: 1.
```

A clearer message earlier on in the `balena push` process would be ideal.

CLI v21.1.0

Reproduction:
```
version: '2.4'

services:
  main:
    image: alpine
    command: sh -c "echo 'hello world' && sleep infinity"
    volumes:
      - /run/dbus:/host/run/dbus:ro
```
